name: 'EKS kubectl'
author: Ian Belcher
description: An action allowing you to integrate with EKS via kubectl in a Github Action, easily...
branding:
  color: 'white'
  icon: 'command'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/miguelaferreira/eks-kubectl-action:latest'
inputs:
  aws_access_key_id:
    description: Your AWS_ACCESS_KEY_ID
    required: true
  aws_secret_access_key:
    description: Your AWS_SECRET_ACCESS_KEY
    required: true
  aws_region:
    description: The region of the cluster
    required: true
  cluster_name:
    description: The name of the cluster you're using
    required: true
  args:
    description: The arguments that you want to pass through to the kubectl command
    required: true
outputs:
  kubectl-out:
    description: The output of the kubectl command
